### PR TITLE
Added SIOT JavaScript library using NATS over WebSockets

### PR DESCRIPTION
**Pull request by bminer**
@cbrake Please let me know your thoughts.  A few things I should note here:

- Single file `siot-nats.js` provides the JavaScript SIOT API over NATS / WebSockets.  I am open to renaming this file or moving it elsewhere in the repo
- `siot-nats.js` is an ES Module that exposes a single `connect` function.
- The return value of `connect` is a Promise that resolves to the connection object.  This object inherits from `nats.ws` connection object, so it has methods like `close`, `publish`, `subscribe`, etc.  But, the connection object also has SIOT specific methods like `getNode` and `subscribePoints`
- Since `siot-nats.js` is an ES Module that imports exclusively CommonJS modules, maybe it should be converted to CommonJS? For now, I did nothing since most bundlers should be able to figure it out.

Usage is something like this:

```js
import { connect } from "./lib/nats"

async function connectAndGetNodes() {
	const conn = await connect()
	const [root] = await conn.getNode("root")
	const children = await conn.getNodeChildren(root.id, { recursive: "flat" })
	return [root].concat(children)
}
```

Anyway, let me know your thoughts!  Thanks!

### CODE REVIEW

**Comment by cbrake** [comment]
This looks good to me -- API looks clean.

I'm fine merging now and we can make changes as needed. Does not look like it should have any affect on existing SIOT JS code.

**Comment by cbrake** [comment]
let me know when you're ready to merge this.

**Comment by bminer** [comment]
I think I'm about ready. Since this has a `package.json` file, I'm thinking about publishing this `lib` folder as its own npm package. Thoughts? Do you like the npm package name `simpleiot-js`?

Thanks!

**Comment by bminer** [comment]
So to be clear, while this repository would contain Go code and JS code, the npm package would only be the contents the `frontend/lib` folder. I might even rename to `frontend/simpleiot-js`...

**Pull request merged**
