### PR TITLE
WIP: NTP Client

### PR DESCRIPTION
**Pull request by bminer**
Just need to finish up some tests

### CODE REVIEW

**Comment by cbrake** [comment]
Looks great! I'd like to do the following yet:

- Elm UI (feel free to do this, or I can)
- Client Documentation
  - describe how to integrate this into system, do they need to remove entries in `/etc/systemd/timesyncd.conf`, or will these take precedence.

**Comment by bminer** [comment]
Agree with the above. I'll let you do the Elm UI, as I'm not quite ready to bite on that just yet. I need to test to see how the `timesyncd.conf.d` files take precedence.

I also probably need to create the `timesyncd.conf.d` folder if it doesn't already exist.

**Comment by cbrake** [comment]
this client currently writes to:

const NTPConfigPath = "/etc/systemd/timesyncd.conf.d/simpleiot.conf"

@kraj do you have any thoughts on how this should integrate with the OS builds, like Yocto?

Looks like we current run as root, but eventually may want to run as non-root user:

https://github.com/simpleiot/simpleiot/blob/master/contrib/siot.service

**Comment by kraj** [comment]
> 



> this client currently writes to:
> 
> const NTPConfigPath = "/etc/systemd/timesyncd.conf.d/simpleiot.conf"
> 
> @kraj do you have any thoughts on how this should integrate with the OS builds, like Yocto?

I think this file should be packaged as part of siot package, its a typical systemd unit drop-in and
they are usually installed and uninstalled by apps. More important is what you want to do in that
file, if its changing the service in a way that other services on the device are impacted them we need
to review that.  

> 
> Looks like we current run as root, but eventually may want to run as non-root user:
> 
> https://github.com/simpleiot/simpleiot/blob/master/contrib/siot.service

yeah non-root is good to run siot.service but this user mght need to be able to be part of net namespace.

**Comment by bminer** [comment]
If `simpleiot.service` is running under user `simpleiot`, you can set the permissions of `/etc/systemd/timesyncd.conf.d/simpleiot.conf` so that it is editable by the process.

**Comment by bminer** [comment]
Also side note, are we using `siot` or `simpleiot`? Trying to stay consistent.

**Comment by cbrake** [comment]
siot is what I typically use:

https://github.com/simpleiot/simpleiot/tree/master/contrib

**Comment by cbrake** [comment]
I'm going to merge this for now to keep code flowing. We can add the Elm UI later.

**Pull request merged**
