### PR TITLE
Cbrake/feature auth

### PR DESCRIPTION
**Pull request by cbrake**
@kdsch what do you think of adopting the golint standards for go documentation? I created a siot_test function in envsetup.sh that runs this as well as some other stuff. I also created a github action that runs this on commit, and likely we can tie into pull requests.

### CODE REVIEW

**Comment by cbrake** [comment]
this is not ready yet, will re-open later.

**Comment by kdsch** [comment]
@cbrake It's a good idea.

**Comment by cbrake** [comment]
@kdsch ok, I think I have this sorted -- if you click on the details above, you'll see golint is complaining about missing documentation on some functions.

**Comment by kdsch** [comment]
Nice.

**Comment by cbrake** [comment]
github actions seem to work pretty well. Anyway, go ahead and merge and fix up when you have a chance.

**Pull request merged**
