### PR TITLE
serial device support

### PR DESCRIPTION
**Pull request by cbrake**
work on #380 

You can read draft of this spec here:

https://github.com/simpleiot/simpleiot/blob/feature-serial/docs/ref/serial.md

### CODE REVIEW

**Comment by cbrake** [comment]
cc: @collinbrake @jeff-jldtech @biosguy @bminer @SuperChrim

Let me know if you have any thoughts.

**Comment by cbrake** [comment]
cc @coledd

**Comment by collinbrake** [comment]
@cbrake Related to the section on CAN in the specification:

The [J1939 reference by Copperhill Tech](https://copperhilltech.com/blog/sae-j1939-programming-with-arduino-multipacket-broadcast-bam-session/) specifies how multi-packet messages need to be sent
   - Broadcast Announce message by the sender
   - The receiving node responds with Clear to Send
   - The message packets that compose the larger multi-packet message are sent one-by-one with appropriate time delay in between
   - Nothing in this reference indicates that this process is automated in any way, it is all handled in the application layer

[This code](https://github.com/cancapture/CANCapture-Resources/blob/master/examples/scripting/bam-transmit-script.c) shows an example of sending a multi-packet message with the CANCapture scripting interface.

**Comment by cbrake** [comment]
thanks @collinbrake. Have you looked at `Transport Protocol` yet?

https://copperhilltech.com/blog/tag/Transport+Protocol

Are BAM messages one-to-many, where Transport Protocol are one-to-one? If so, it seems we would want a one-to-one protocol. (I many not be understanding this correctly).  

Thanks!

**Comment by cbrake** [comment]
serial device node created:

image

**Comment by bminer** [comment]
Looks pretty good to me. There may be applications where clock sync is more important and needs to be more complicated, but in the spirit of keeping it **simple**, I think this will work just fine. Nice work so far!

**Comment by jeff-jldtech** [comment]
@cbrake @collinbrake 

I can give you a 30 minute primer on J1939 Transport Protocol (BAM and Point to Point). Let me know if you're ionterested.

**Comment by cbrake** [comment]
@jeff-jldtech I'm definitely interested. My schedule is pretty flexible next week so lets sync up then.

**Comment by jeff-jldtech** [comment]
@cbrake @collinbrake 

Will 4:00 Monday work?

**Comment by collinbrake** [comment]
@jeff-jldtech @cbrake 

4:00 today works for me. I look forward to meeting you Jeff, if that still works for you.

**Pull request merged**
