### PR TITLE
Fix array decode issues to zero length array

### PR DESCRIPTION
**Pull request by cbrake**

### CODE REVIEW

**Comment by bminer** [comment]
I am reviewing this now... at first glance, I'm not sure why the test failed and why a change is needed...

**Comment by bminer** [comment]
Okay, I see the bug now. This PR does not fully address the bug. Should I make a new PR for this?

I see two issues here both in `SetValue`:

One is here: https://github.com/simpleiot/simpleiot/blob/9c610381fcbbf0510f54569307979374287c3081/data/decode.go#L109-L114
The other is potentially here: https://github.com/simpleiot/simpleiot/blob/9c610381fcbbf0510f54569307979374287c3081/data/decode.go#L70

**Comment by cbrake** [comment]
sure, ideas welcome!

**Comment by bminer** [comment]
Edited my last post, but I think this is very close to fixing the bug, but I will checkout this branch, make some minor edits and open a new PR.

**Comment by cbrake** [comment]
thanks @bminer

**Comment by bminer** [comment]
So, I decided to keep your solution but also fix another issue in the code that may or may not matter. Thanks!

**Pull request merged**
