### PR TITLE
goreleaser.yml: Add riscv64 to release artifacts on linux platforms

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by kraj** [comment]
@cbrake can we merge this and see if it can start building riscv64 binaries. We now package released binaries in yoe, which helps in packaging siot on aarch64 build hosts ( since we can not build it from source there due to elm compiler not being available for aarch64 hosts ). Once we have riscv64 release artifacts, CI/CD for yoe distro can use siot for both rpi4/visionfive2/qemuarm64 targets which are our primary targets

**Comment by cbrake** [comment]
thanks @kraj!

**Comment by cbrake** [comment]
riscv binary uploaded with 0.12.3 release -- build at least worked :smiley:

**Comment by kraj** [comment]
> riscv binary uploaded with 0.12.3 release -- build at least worked 😃

cool! I will download it on my visionfive2 board and see if it works too.

**Comment by cbrake** [comment]
amazing!

**Pull request merged**
