### PR TITLE
use nats for user auth requests (instead of direct calls to DB)

### PR DESCRIPTION
**Pull request by cbrake**
implements #326

### CODE REVIEW

**Comment by cbrake** [comment]
@bminer can you review this API and let me know if you have any thoughts?

I'm wondering if we should be defining special protobuf messages for this kind of stuff, or just use points?

Also had a similar question this morning about notifications/messages -- currently custom structs. Now that we've figured out encoding for arrays/maps in points, I wonder if bundles of points would be a better encoding? Then we could automatically write to influx. Once we switch to sqlite and normalize the data, then a node could 1000's of points, or messages/notifications could just be encoded as another node and be as child of the node that sent the notification, or received the message. Obviously, we'd need to be careful what data we fetched and sent to the UI so we did not overload it. Or, the node could just store that last notification/message, and you have to look in TSD (influx) for history. This probably makes a lot of sense, as then you can have a handle (node ID) to query for messages. But, then why not just store messages/notifications as points in the actual node ... the node points would again just hold the latest message/notification, which is similar to sensors values -- the node just displays the latest state.

**Comment by bminer** [comment]
Here are my thoughts:

- My thinking is that messages and notifications should be separated from points because they aren't really a part of the state of the node, but I can be persuaded. That said, I suppose my opinion of this is mostly neutral.
- My understanding is that the `auth.user` request returns all of the nodes a user can access. In that case, we need to prevent unauthorized fetching of nodes directly, correct? For example, I presume that you shouldn't be allowed to fetch the root node with a request to `node.root` anymore?

**Comment by bminer** [comment]
Also, at the NATS layer, how do we implement security? (i.e. prevent subscriptions on the wildcard subjects)

**Comment by cbrake** [comment]
@bminer here is what I ended up with for API (nats/node.go) -- I think using nodes and points ended up pretty clean in this case:

```go
// UserCheck sends a nats message to check auth of user
// This function returns user nodes and a JWT node which includes a token
func UserCheck(nc *natsgo.Conn, email, pass string) ([]data.NodeEdge, error) {
        points := data.Points{
                {Type: data.PointTypeEmail, Text: email},
                {Type: data.PointTypePass, Text: pass},
        }

        pointsData, err := points.ToPb()
        if err != nil {
                return []data.NodeEdge{}, err
        }

        nodeMsg, err := nc.Request("auth.user", pointsData, time.Second*20)
        if err != nil {
                return []data.NodeEdge{}, err
        }

        nodes, err := data.PbDecodeNodesRequest(nodeMsg.Data)

        if err != nil {
                return []data.NodeEdge{}, err
        }

        return nodes, nil
}
```

We'll probably want something similar in the JS API now that the backend supports this.

Will need to do some more thinking about msg/notifications. 

The NATS auth.user api only returns a JWT and the user nodes at this point -- you still need to fetch nodes for user using one of the other APIs once you know the user ID.

I've still not done any work to prevent users from accessing nodes they don't have access to -- this still needs some more thought which I plan to continue in [ADR-2](https://github.com/simpleiot/simpleiot/pull/283).

For now, the UI displaying only the nodes a user has access to is a convenience, not a security restriction. They can obviously write their own client and access everything if they have an account on the system.

**Pull request merged**
