### PR TITLE
Modbus protocol improvements

### PR DESCRIPTION
**Pull request by quentinmit**
- Adds support for Write Multiple Coils and Write Multiple Registers.
- Properly checks packet length only on requests (not on responses, which are often shorter).
- Adds test cases to verify normal and error behavior for all supported function codes.

### CODE REVIEW

**Comment by quentinmit** [comment]
Also, obligatory clackety proof of life: https://photos.app.goo.gl/rbA1WHtZy2qeHh1s5

**Comment by cbrake** [comment]
@quentinmit thanks for the great improvements and neat video!

For some reason, github actions are not running on your PRs -- I've just been pulling in your changes and merging manually, but not sure why github is not running my build checks in your forked repo? Seems like it should:

* https://github.community/t/github-action-not-triggered-on-pull-request/18009/3

**Comment by cbrake** [comment]
getting a minor go vet error:

```
# github.com/simpleiot/simpleiot/modbus
Error: modbus/pdu_test.go:172:34: call of t.Logf copies lock value: github.com/simpleiot/simpleiot/modbus.Regs contains sync.RWMutex
Error: Process completed with exit code 1.
```
Fixed with: https://github.com/simpleiot/simpleiot/pull/121/commits/d3b9d95e939351f3b82eec7760c095ee9b59edd3

Thanks for the PR -- merged.

**Comment by cbrake** [comment]
@quentinmit -- so you are turning a P1AM-100 into a low cost modbus IO device -- that is really neat idea.

**Pull request merged**
