### PR TITLE
Added `siot_test_frontend_lib` script to envsetup

### PR DESCRIPTION
**Pull request by bminer**
Along with some misc. fixes / cleanup

### CODE REVIEW

**Comment by bminer** [comment]
One thing I noticed is that `--resetStore` runs silently for this test without prompting the user.  Should we change this?

**Comment by cbrake** [comment]
what if we would use a different store file than the default when running tests? 

pass -store option to serve.

This way we won't delete the default (working) store than may have a nice setup in it that we don't want cleaned.

**Comment by bminer** [comment]
> what if we would use a different store file than the default when running tests?

This had crossed my mind before, but I completely forgot to do it this way.  I'll fix.  Thanks!

**Comment by cbrake** [comment]
Looks great, thanks!

**Pull request merged**
